### PR TITLE
Added volume sliders

### PR DESCRIPTION
**Pull request by chanmol1999**
## added slider to adjust volume
fixes (#16 )

)

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by numerative** [comment]
Hey @chanmol1999,
Please pay attention to requirements mentioned in the issue.

1. Two separate volume sliders are required - 1. for Ticking sound and 2. for Ringing sound.
2. These volume sliders are required in the `SettingsActivity` and not the MainActivity.

Moreover, since your UI changes are not to be merged, please `drop` that commit from history.

Please make the above changes so that we can merge this PR.

**Review by numerative — CHANGES_REQUESTED** [review]
As above ^

**Comment by chanmol1999** [comment]
Ticking sound for sound of timer but ringing sound for what please comment

**Comment by numerative** [comment]
After the session ends a ringing tone is played. Hit the ✅ to hear the sound 🔊

**Pull request closed without merging**
