### PR TITLE
Uiissue

### PR DESCRIPTION
**Pull request by chanmol1999**
## I have tried my best to make up the UI .Please recommend changes if needed.As far as running status is concerned i think it must be a separate issue.
the mockup UI given in settings,i think this one is a better one.But if you insist i will try to change that.
Please run the app to check the visibility of work sessions completed.

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by chanmol1999** [comment]
screenshots

screenshot_20181229_135312
screenshot_20181229_135840

**Comment by chanmol1999** [comment]
screenshots 
screenshot_20181229_143503
screenshot_20181229_143458

**Comment by ghost** [comment]
@chanmol1999 looking great I have provided link in issue about mockup so you can go there and download all resources and font there is small change in stop button so I will finish it by tonight and reupload it I already mentioned colors in separate txt file for more you can contact me on slack id Hannan Shaikh.abnd

**Comment by numerative** [comment]
This is going good @chanmol1999. :+1: 

Use the new settings button image resource that @iamhshaikh uploads by tonight.

**Comment by ghost** [comment]
@chanmol1999 use this link [https://drive.google.com/drive/folders/1judig0EcEG7m6fGG9NpEk8BwSe1HD3e-?usp=sharing](url)

I have included all drawables with multiple density, and setting icon in svg format so you can import it as vector in application also font faces. also go through doc 
cc: @numerative

**Comment by chanmol1999** [comment]
is this final @ numerative should i update the pr.
cc: @iamhshaikh 
screenshot_20181229_215055

**Comment by numerative** [comment]
Looks good!
Have you updated the fonts? I am not sure if they were provided by @iamhshaikh.

**Comment by chanmol1999** [comment]
don't know about fonts @numerative @iamhshaikh

**Comment by ghost** [comment]
Check there are two folders Raleway and Quicksand so ttf files of both fonts with all types i mean bold italic are present just you have to make xml file for fonts and define your family there

**Comment by chanmol1999** [comment]
Is this on final @numerative should i update the pr

screenshot_20181230_020203
screenshot_20181230_020215

**Comment by ghost** [comment]
Dropdown menu rounded white background? and did you used font I provided ? @chanmol1999

**Comment by chanmol1999** [comment]
Please review it @numerative i have made all necessary changes

**Comment by chanmol1999** [comment]
screenshot_20181230_161213
screenshot_20181230_161156

**Comment by numerative** [comment]
@chanmol1999 there seems to have been a problem with the last merge commit. Probably you didn't resolve the conflicts properly.

**Comment by chanmol1999** [comment]
Now you can review it @numerative

**Comment by numerative** [comment]
Check line number 500 of the MainActivity. There's an error there.

**Comment by numerative** [comment]
I've made corrections. Pushing changes.

**Comment by numerative** [comment]
This has been merged. Manually closing the issue.

Thanks @chanmol1999 for your contribution.

**Pull request closed without merging**
