### PR TITLE
Updated alert dialog according to theme

### LINKED ISSUE #58: Design the Alert Dialog as per the theme
Design the alert dialog box to match the app's theme.

screen

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### PR DESCRIPTION
**Pull request by chanmol1999**
## Updated alert dialog box according to theme

Fixes #58 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by chanmol1999** [comment]
ui changes as 
screenshot_20190102_162225

**Comment by numerative** [comment]
Can be prettier:
- Fonts look too big for the alertdialog. Covering much of the space.
- Can the background be same as the app's?
- Skip break can remain white.

**Comment by chanmol1999** [comment]
screenshot_20190102_171423

**Comment by numerative** [comment]
One last change:
- Please use the fonts used in the ActionBar to display app name and in the settings activity.

**Comment by chanmol1999** [comment]
Please review it @numerative

**Comment by numerative** [comment]
Well done @chanmol1999!

**Pull request merged**
