### PR TITLE
Changed about us activity

### LINKED ISSUE #59: Move the About Us text to Settings Activity
Move the About Us text to SettingsActivity and delete the AboutUs Activity.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### PR DESCRIPTION
**Pull request by chanmol1999**
## Now about us is contained in settings activity

Fixes #59 

## Type of change
Just put an x in the [] which are valid.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by numerative** [comment]
Since this issue was taken up by @iamhshaikh, we'll wait for him to submit his PR. 

Better of the two choices will then be merged.

**Comment by numerative** [comment]
@chanmol1999, 
In the meantime... The current about us text is not at all consistent with the design of the SettingsActivity.  Please consider changing it.

**Comment by chanmol1999** [comment]
updated the about us @numerative

**Comment by chanmol1999** [comment]
I have added a toast message to view terms of use instead of about us and inhibited the about us from appearing directly on settings activity instead i added scroll bar.

**Comment by numerative** [comment]
@chanmol1999 , guess what! You removed the line for `initspinner();` method call. :man_shrugging: 

Anyway, the idea of showing a Toast is novel and we'll keep it. However, what's up with the formatting??

Can't we keep the white coloured text and provide enough margin to the text so that it is consistent with the old title, spinner and seekbar?

Other suggested changes.
- It's not exactly terms of use, the title can be **About Tamétû App**
- and instead of Developers we can use **Developed by**

**Pull request closed without merging**
