### PR TITLE
Resolved work session count after 8 hours

### LINKED ISSUE #14: WORK_SESSION_COUNT resets after 8 hours of inactivity
Currently,the WORK_SESSION_COUNT never resets to 0, and this has implications since it controls the work/break logic. e.g. If you completed 3 sessions today and complete the 4th one next day, you will be prompted to Start Long Break on the very first session of your day. 

### REQUIRED
Reset the WORK_SESSION_COUNT to zero if there is a difference of 4 hours between the end of current session and previous session.

This will ensure Long break doesn't popup unexpectedly.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### PR DESCRIPTION
**Pull request by chanmol1999**
## Resolved work session count after 8 hours.Added a timer when app background if inactive for 4 hours the worksession count will reset to 0 for improvising functionality of start long break after.
Also applied ctrl+alt+l as asked.

Fixes #14 

## Type of change
Just put an x in the [] which are valid.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

### CODE REVIEW

**Comment by numerative** [comment]
This is not the desired solution and it is not working. 
Ideally, the solution would involve storing (preferably via sharedPreferences) a timestamp of the _end_ of last activity (session or break) and comparing it with the timestamp of the start of next activity (session or break). If the difference between the two is greater than 8 hours, then reset the work_session_count.

**Comment by chanmol1999** [comment]
I have made for difference 4 hours
Everytime when the app is stop or destroyed a countdown timer starts and resets the work session counts which currently has no relation with work sessions completed displayed on screen

**Comment by numerative** [comment]
I understand we have different counters. I tested it by reducing the time to just 4 seconds and clearing the app from memory. The counter didn't reset and the long break appeared as it was supposed to appear. The countdowntimer might just not have worked in the background.

Moreover, the code is triggered at onCreate - hence the counter resets 4 seconds after the app is started. This is also not the expected behaviour.

**Comment by chanmol1999** [comment]
Now i think it is working as expected .Please review it.

**Comment by numerative** [comment]
Hey @chanmol1999, 
Please do bit of testing before submitting a PR.
It's good that you are storing timestamps in the sharedpreferences. This a required functionality.

But is storing the value during the onPause and onResume really a good idea? Does it achieve the purpose? Moreover, resuming after the `(resume-pause>=14400)` have elapsed, the app would never prompt for a long break. Why?

I appreciate your contributions for this project, but you are leaving all the testing on the maintainers - not a good practice. I hope you'll take this constructively.

Now, since you've written most of the code, it should be easier for you to fix it. But before you code, please do explain how do you plan to address the above issues.

PS: Don't forget `Ctrl + Alt + L`.

**Comment by chanmol1999** [comment]
I am not able to find a correct solution to this problem so i will not be able to work on this further @numerative if i could solve i propose another pr

**Comment by numerative** [comment]
@chanmol1999 the solution is now pretty simple.

All you have to do is put the code for pause in stopTimerUtils and resume in `case R.id.timer_button_main:` in the MainActivity.

The `resume - pause` will also be placed in the above mentioned `case`.

**Pull request merged**
