### PR TITLE
Fixed screen orientation

### LINKED ISSUE #17: Add spinner for long break interval [XML only]
Add a spinner in Settings Activity.
Title: _Start Long Break after_
Spinner Values: _2_ , _3_ , _4_ ,  _5_, _6_

Scope of this issue covers only XML changes required.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### LINKED ISSUE #24: App must support portrait mode only
The current UI of the App demands it to be available in portrait mode only.

### Steps to reproduce
change in manifest file.

### Expected behaviour
Must show only in portrait mode as standard apps.

### Actual behaviour
Currently landscape and portrait both exists.

### Would you like to work on the issue?
Yes.

-----------------------------------

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### PR DESCRIPTION
**Pull request by chanmol1999**
##the current layout demands app to be in portrait mode only.

Fixes #24 and fixes #17  

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by numerative** [comment]
Perfect!
Thanks for incorporating the changes. This will be merged tomorrow.

**Review by codersanjeev — APPROVED** [review]

**Comment by chanmol1999** [comment]
also fixes #17 as required

**Review by numerative — CHANGES_REQUESTED** [review]
@chanmol1999 One change.
The values for start long break after are not in _minutes_ but in _sessions_.
So, it would be
_2 sessions_, _3 sessions_ and so on.

**Comment by chanmol1999** [comment]
Fixed minutes--> sessions

**Pull request merged**
